//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtDevops.Dialogs.Root {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RootStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RootStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtDevops.Dialogs.Root.RootStrings", typeof(RootStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguimiento de siniestros.
        /// </summary>
        internal static string AccidentChoice {
            get {
                return ResourceManager.GetString("AccidentChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago de deducibles.
        /// </summary>
        internal static string DeductiblesChoice {
            get {
                return ResourceManager.GetString("DeductiblesChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo siento, esa fue una respuesta inválida, por favor, selecciona una adecuada.
        /// </summary>
        internal static string InvalidChoice {
            get {
                return ResourceManager.GetString("InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta tu factura.
        /// </summary>
        internal static string InvoiceChoice {
            get {
                return ResourceManager.GetString("InvoiceChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta tu póliza.
        /// </summary>
        internal static string PolicyChoice {
            get {
                return ResourceManager.GetString("PolicyChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haz una pregunta.
        /// </summary>
        internal static string QnAPrompt {
            get {
                return ResourceManager.GetString("QnAPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola! Ahora estás en el diálogo principal ¿Cuál es tu nombre?.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola de nuevo al diálogo principal.
        /// </summary>
        internal static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Acerca de qué quieres platicar {0}?.
        /// </summary>
        internal static string WhichFlowPrompt {
            get {
                return ResourceManager.GetString("WhichFlowPrompt", resourceCulture);
            }
        }
    }
}
